spring:
  datasource:
    username: upms
    password: upms
    url: jdbc:postgresql://127.0.0.1:5432/upms?useUnicode=true&amp;characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver

org:
  cuber:
    gen:
      conf:
        catalog:
        schema:
        dto:
          template: /dto.btl
          destProject:
          destPackage:
          rootClass: org.cuber.stub.repo.StubDTO
        mapper:
          template: /mapper.btl
          destProject:
          destPackage:
          rootClass: org.cuber.stub.repo.Mapper
        xml:
          template: /xml.btl
          destProject:
          destPackage:
        vo:
          template: /vo.btl
          destProject:
          destPackage:
          rootClass: org.cuber.stub.vo.StubVO
        service:
          template: /service.btl
          destProject:
          destPackage:
          templateImpl: /serviceImpl.btl
        ctrl:
          template:
          destProject:
          destPackage:
        view:
          template:
          destProject:
          destPackage:
        tables:
          - tableName:
            dtoName: