spring:
  datasource:
    username: foundation
    password: foundation
    url: jdbc:postgresql://127.0.0.1:5432/foundation?useUnicode=true&amp;characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver

org:
  cuber:
    gen:
      conf:
        catalog:
        schema:
        dto:
          template: /dto.btl
          destProject: D:\project\java\corp\old\unite-foundation\foundation-dal\src\main\java
          destPackage:  org.cuber.foundation.dto
          rootClass: org.cuber.stub.repo.StubDTO
        mapper:
          template: /mapper.btl
          destProject: D:\project\java\corp\old\unite-foundation\foundation-dal\src\main\java
          destPackage: org.cuber.foundation.mapper
          rootClass: org.cuber.stub.repo.Mapper
        xml:
          template: /xml.btl
          destProject: D:\project\java\corp\old\unite-foundation\foundation-dal\src\main\resources
          destPackage:  mapper
        vo:
          template: /vo.btl
          destProject: D:\project\java\corp\old\unite-foundation\foundation-facade\src\main\java
          destPackage: org.cuber.foundation.vo
          rootClass: org.cuber.stub.vo.StubVO
        service:
          template: /service.btl
          destProject: D:\project\java\corp\old\unite-foundation\foundation-biz\src\main\java
          destPackage: org.cuber.foundation.single.service
          templateImpl: /serviceImpl.btl
        ctrl:
          template: /controller.btl
          destProject: D:\project\java\corp\old\unite-foundation\foundation-web\src\main\java
          destPackage: org.cuber.foundation.controller
        view:
          template:
          destProject:
          destPackage:
        tables:
          - tableName: t_sub_table_conf
            dtoName: DSubTableConf
          - tableName: t_country_3166
            dtoName: Country
          - tableName: t_currency_4217
            dtoName: Currency
          - tableName: t_dict_data
            dtoName: DictData
          - tableName: t_dict_type
            dtoName: DictType