spring:
  datasource:
    username: sso
    password: sso
    url: jdbc:postgresql://127.0.0.1:5432/sso?useUnicode=true&amp;characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver

org:
  cuber:
    gen:
      conf:
        catalog:
        schema:
        dto:
          template: /dto.btl
          destProject: D:\project\java\corp\new\union-sso\sso-dal\src\main\java
          destPackage:  org.cuber.sso.dto
          rootClass: org.cuber.stub.repo.StubConfDTO
        mapper:
          template: /mapper.btl
          destProject: D:\project\java\corp\new\union-sso\sso-dal\src\main\java
          destPackage: org.cuber.sso.mapper
          rootClass: org.cuber.stub.repo.Mapper
        xml:
          template: /xml.btl
          destProject: D:\project\java\corp\new\union-sso\sso-dal\src\main\resources
          destPackage:  mapper
        vo:
          template: /vo.btl
          destProject: D:\project\java\corp\new\union-sso\sso-facade\src\main\java
          destPackage: org.cuber.sso.vo
          rootClass: org.cuber.stub.vo.StubConfVO
        service:
          template: /service.btl
          destProject: D:\project\java\corp\new\union-sso\sso-biz\src\main\java
          destPackage: org.cuber.sso.single.service
          templateImpl: /serviceImpl.btl
        ctrl:
          template: /controller.btl
          destProject: D:\project\java\corp\new\union-sso\sso-web\src\main\java
          destPackage: org.cuber.sso.controller
        view:
          template:
          destProject:
          destPackage:
        tables:
          - tableName: t_user
            dtoName: UserEntity
          - tableName: t_login_log
            dtoName: LoginLog
          - tableName: t_operate_log
            dtoName: OperateLog
          - tableName: t_user_group
            dtoName: UserGroupEntity
          - tableName: t_role
            dtoName: RoleEntity
          - tableName: t_resource
            dtoName: Resource
          - tableName: tr_user_group
            dtoName: TrUserGroup
          - tableName: tr_user_role
            dtoName: TrUserRole
          - tableName: tr_role_resource
            dtoName: TrRoleResource