spring:
  datasource:
    username: upms
    password: upms
    url: jdbc:postgresql://127.0.0.1:5432/upms?useUnicode=true&amp;characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver

org:
  cuber:
    gen:
      conf:
        catalog:
        schema:
        dto:
          template: /dto.btl
          destProject: D:\project\java\corp\unite-upms\upms-dal\src\main\java
          destPackage:  org.cuber.upms.dto
          rootClass: org.cuber.stub.repo.StubDTO
        mapper:
          template: /mapper.btl
          destProject: D:\project\java\corp\unite-upms\upms-dal\src\main\java
          destPackage: org.cuber.upms.mapper
          rootClass: org.cuber.stub.repo.Mapper
        xml:
          template: /xml.btl
          destProject: D:\project\java\corp\unite-upms\upms-dal\src\main\resources
          destPackage:  mapper
        vo:
          template: /vo.btl
          destProject: D:\project\java\corp\unite-upms\upms-facade\src\main\java
          destPackage: org.cuber.upms.vo
          rootClass: org.cuber.stub.vo.StubVO
        service:
          template: /service.btl
          destProject: D:\project\java\corp\unite-upms\upms-biz\src\main\java
          destPackage: org.cuber.upms.single.service
          templateImpl: /serviceImpl.btl
        ctrl:
          template: /controller.btl
          destProject: D:\project\java\corp\unite-upms\upms-web\src\main\java
          destPackage: org.cuber.upms.controller
        view:
          template:
          destProject:
          destPackage:
        tables:
          - tableName: t_user
            dtoName: UniteUser