spring:
  datasource:
    username: basic
    password: basic
    url: jdbc:postgresql://127.0.0.1:5432/basic?useUnicode=true&amp;characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver

org:
  cuber:
    gen:
      conf:
        catalog:
        schema:
        dto:
          template: /dto.btl
          destProject: D:\project\java\corp\old\basic-service\basic-dal\src\main\java
          destPackage:  org.cuber.stub.basic.dto
          rootClass: org.cuber.stub.repo.StubConfDTO
        mapper:
          template: /mapper.btl
          destProject: D:\project\java\corp\old\basic-service\basic-dal\src\main\java
          destPackage: org.cuber.stub.basic.mapper
          rootClass: org.cuber.stub.repo.Mapper
        xml:
          template: /xml.btl
          destProject: D:\project\java\corp\old\basic-service\basic-dal\src\main\resources
          destPackage:  mapper
        vo:
          template: /vo.btl
          destProject: D:\project\java\corp\old\basic-service\basic-facade\src\main\java
          destPackage: org.cuber.stub.basic.vo
          rootClass: org.cuber.stub.vo.StubConfVO
        service:
          template: /service.btl
          destProject: D:\project\java\corp\old\basic-service\basic-biz\src\main\java
          destPackage: org.cuber.stub.basic.single.service
          templateImpl: /serviceImpl.btl
        ctrl:
          template: /controller.btl
          destProject: D:\project\java\corp\old\basic-service\basic-web\src\main\java
          destPackage: org.cuber.foundation.controller
        view:
          template:
          destProject:
          destPackage:
        tables:
          - tableName: t_cache_def
            dtoName: CacheDefEntity